### PR TITLE
Factor out Section_X methods for Global, Export, Start, Element, Code, and Data sections

### PR DESCRIPTION
**Pull request by munik**
This change is intended to work toward one of the current development objectives:
- Improve exceptions thrown from problems found during compilation or execution.

For issue #35, this would have resulted in the following additional line
in the stack trace:
`   at WebAssembly.Runtime.Compile.Section_Global(...)`

If this change is deemed desirable, I'd like to make similar changes to
the remaining section cases. Some of them will present the challenge of
multiple local variable mutations (e.g. Section.Memory) which I would
intend to solve with multiple return values.

Note: I also promoted the `TypeAttributes` local constants (e.g.
`internalFunctionAttributes`) to member constants because they'll need
to be referenced in the methods that will be factored out and there's no
need to pass them as parameters since they're constant.

@RyanLamansky I hope you don't mind I wanted to take a stab at one of the (easier) development objectives and improve the stack traces in particular for issue #35. This is a simple technique we've used at my job to improve stack traces for large methods. If you deem this technique to have issues, no sweat -- please let me know if there's a better method you'd recommend!

### CODE REVIEW

**Comment by RyanLamansky** [comment]
This will take some time to review due to the large number of "changed" lines (I should get to it this weekend), and it's not quite the naming scheme I'd go with, but this would definitely help with narrowing down compiler issues.

**Comment by munik** [comment]
@RyanLamansky Please let me know the naming scheme you want, and I can update it!

In case you're interested, I use [Beyond Compare](https://www.scootersoftware.com/download.php) for differencing. It allows you to set custom alignments. Doing this made it easy for me to verify the epilogue of FromBinary as well as the individual methods that were factored out. I put the factored out methods in the same order as the cases in the switch to facilitate that.

E.g.
image

**Review by RyanLamansky — APPROVED** [review]
As far as naming goes, the pattern used throughout the application is that static/const members follow PascalCase format--no underscores and never a lowercase first letter.

The new arrangement is non-public, so it's not a breaking change to alter it later. I can leave this PR open if you'd like to make this change, otherwise I can merge it and change it myself 🙂

**Comment by munik** [comment]
Thank you for the review! I'll be honest I didn't pay close enough attention to the code style. I'll pay more attention to that next time.

I pushed a fixup that corrects the naming in case you'd like to review. I also fixed the constants that were factored out in addition to the methods, and I used VS Code's automatic rename refactoring for maximum safety.

If you're good with the changes or don't feel the need to review, I'll squash, fix the commit comment to refer to the final names and merge

**Review by RyanLamansky — APPROVED** [review]

**Comment by munik** [comment]
@RyanLamansky Oh no, there was an unsquashed fixup in there! Sorry -- maybe I should have called that out

**Comment by RyanLamansky** [comment]
No worries, I like my history to be a little messy 🙂

**Comment by munik** [comment]
@RyanLamansky Ha ha, okay, I can roll with that 😄

**Pull request merged**
